global:
  namespace: shopflow

backend:
  replicaCount: 2
  image:
    repository: shopflow-backend
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 5000

frontend:
  replicaCount: 2
  image:
    repository: shopflow-frontend
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    port: 80
    nodePort: 30080

postgres:
  database: shopflow
  user: shopuser
  password: shoppassword

redis:
  port: 6379
